name: Testing
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions:
          - 8.0
          - 8.1
        dependency-levels:
          - 'highest'
        experimental:
          - false
        include:
          - php-versions: 8.0
            dependency-levels: 'lowest'
            experimental: false
      fail-fast: false
    continue-on-error: ${{ matrix.experimental }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Validating PHP syntax
      run: find ./{src,tests}/ -type f -name '*.php' -print0 | xargs -0 -L 1 -P 4 -- php -l

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      uses: ramsey/composer-install@v1
      with:
        dependency-versions: "${{ matrix.dependency-levels }}"
        composer-options: "--prefer-dist"

    - name: PhpUnit
      run: ./vendor/bin/phpunit
